#!/bin/bash
file="$1"
case "$file" in
  *.py) python3 "$file" ;;
  *.js) node "$file" ;;
  *.ts) npx ts-node "$file" ;;
  *.java) javac "$file" && java "${file%.java}" ;;
  *.cpp) g++ "$file" -o main && ./main ;;
  *.c) gcc "$file" -o main && ./main ;;
  *.cs) mcs "$file" && mono "${file%.cs}.exe" ;;
  *.go) go run "$file" ;;
  *.rb) ruby "$file" ;;
  *.php) php "$file" ;;
  *.rs) rustc "$file" && ./$(basename "$file" .rs) ;;
  *.sh) bash "$file" ;;
  *.swift) swift "$file" ;;
  *.kt) kotlinc "$file" -include-runtime -d main.jar && java -jar main.jar ;;
  *.scala) scalac "$file" && scala "${file%.scala}" ;;
  *) echo "Unknown file type: $file" ;;
esac
